-- =========================================================
-- TOWER OF CARDS SYSTEM
-- Creación de tablas
-- =========================================================


-- =========================================================
-- SCHEMA: SECURITY
-- =========================================================

CREATE TABLE security.role (
    role_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);


CREATE TABLE security."user" (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role_id INTEGER NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_user_role
        FOREIGN KEY (role_id)
        REFERENCES security.role(role_id)
);


-- =========================================================
-- SCHEMA: CARDS
-- =========================================================

CREATE TABLE cards.card (
    card_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_name VARCHAR(100) NOT NULL UNIQUE,
    value INTEGER NOT NULL,
    type VARCHAR(20) NOT NULL,
    effect VARCHAR(255),
    max_quantity INTEGER NOT NULL,
    rarity VARCHAR(20) NOT NULL,
    description VARCHAR(255) NOT NULL,

    CONSTRAINT chk_card_value
        CHECK (value >= 0),

    CONSTRAINT chk_card_max_quantity
        CHECK (max_quantity > 0)
);


-- =========================================================
-- SCHEMA: PLAYERS
-- =========================================================

CREATE TABLE players.player (
    player_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_player_user
        FOREIGN KEY (user_id)
        REFERENCES security."user"(user_id)
);

CREATE TABLE players.deck (
    deck_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id INTEGER NOT NULL,
    name VARCHAR(50) NOT NULL DEFAULT 'Mazo',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_deck_player
        FOREIGN KEY (player_id)
        REFERENCES players.player(player_id)
);


CREATE TABLE players.deck_card (
    deck_id INTEGER NOT NULL,
    card_id INTEGER NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT chk_deck_card_quantity
        CHECK (quantity > 0),

    CONSTRAINT pk_deck_card
        PRIMARY KEY (deck_id, card_id),

    CONSTRAINT fk_deck_card_deck
        FOREIGN KEY (deck_id)
        REFERENCES players.deck(deck_id),

    CONSTRAINT fk_deck_card_card
        FOREIGN KEY (card_id)
        REFERENCES cards.card(card_id)
);


-- =========================================================
-- SCHEMA: TOURNAMENTS
-- =========================================================

CREATE TABLE tournaments.tournament (
    tournament_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    date DATE NOT NULL,
    format VARCHAR(30) NOT NULL,
    num_players INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    organizer_id INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_tournament_organizer
        FOREIGN KEY (organizer_id)
        REFERENCES security."user"(user_id),

    CONSTRAINT chk_tournament_num_players
        CHECK (num_players > 0)
);


CREATE TABLE tournaments.round (
    round_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id INTEGER NOT NULL,
    number INTEGER NOT NULL,
    name VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_round_tournament
        FOREIGN KEY (tournament_id)
        REFERENCES tournaments.tournament(tournament_id),

    CONSTRAINT uq_round_tournament_number
        UNIQUE (tournament_id, number),

    CONSTRAINT chk_round_number
        CHECK (number > 0)
);

CREATE TABLE tournaments.tournament_registration (
    tournament_registration_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id INTEGER NOT NULL,
    player_id INTEGER NOT NULL,
    registered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_tournament_registration_tournament
        FOREIGN KEY (tournament_id)
        REFERENCES tournaments.tournament(tournament_id),

    CONSTRAINT fk_tournament_registration_player
        FOREIGN KEY (player_id)
        REFERENCES players.player(player_id),

    CONSTRAINT uq_tournament_registration_unique
        UNIQUE (tournament_id, player_id)
);


CREATE TABLE tournaments.round_deck_selection (
    round_deck_selection_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round_id INTEGER NOT NULL,
    player_id INTEGER NOT NULL,
    deck_id INTEGER NOT NULL,
    selected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_round_deck_selection_round
        FOREIGN KEY (round_id)
        REFERENCES tournaments.round(round_id),

    CONSTRAINT fk_round_deck_selection_player
        FOREIGN KEY (player_id)
        REFERENCES players.player(player_id),

    CONSTRAINT fk_round_deck_selection_deck
        FOREIGN KEY (deck_id)
        REFERENCES players.deck(deck_id),

    CONSTRAINT uq_round_deck_selection_unique
        UNIQUE (round_id, player_id)
);


-- =========================================================
-- SCHEMA: MATCHES
-- =========================================================

CREATE TABLE matches.match (
    match_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round_id INTEGER NOT NULL,
    deck1_id INTEGER NOT NULL,
    deck2_id INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_match_round
        FOREIGN KEY (round_id)
        REFERENCES tournaments.round(round_id),

    CONSTRAINT fk_match_deck1
        FOREIGN KEY (deck1_id)
        REFERENCES players.deck(deck_id),

    CONSTRAINT fk_match_deck2
        FOREIGN KEY (deck2_id)
        REFERENCES players.deck(deck_id),

    CONSTRAINT chk_match_different_decks
        CHECK (deck1_id <> deck2_id)
);


CREATE TABLE matches.result (
    result_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id INTEGER NOT NULL UNIQUE,
    winner_id INTEGER NOT NULL,
    end_phase VARCHAR(20) NOT NULL,
    player1_final_life INTEGER NOT NULL,
    player2_final_life INTEGER NOT NULL,
    player1_points INTEGER NOT NULL,
    player2_points INTEGER NOT NULL,
    date TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_result_match
        FOREIGN KEY (match_id)
        REFERENCES matches.match(match_id),

    CONSTRAINT fk_result_winner
        FOREIGN KEY (winner_id)
        REFERENCES players.deck(deck_id)
);


CREATE TABLE matches.match_deck_card (
    match_deck_card_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id INTEGER NOT NULL,
    card_id INTEGER NOT NULL,
    player_slot INTEGER NOT NULL,
    state VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_match_deck_card_match
        FOREIGN KEY (match_id)
        REFERENCES matches.match(match_id),

    CONSTRAINT fk_match_deck_card_card
        FOREIGN KEY (card_id)
        REFERENCES cards.card(card_id),

    CONSTRAINT chk_match_deck_card_slot
        CHECK (player_slot IN (1, 2))
);


CREATE TABLE matches.match_player_state (
    match_id INTEGER NOT NULL,
    player_slot INTEGER NOT NULL,
    current_life INTEGER,
    current_shield INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_match_player_state
        PRIMARY KEY (match_id, player_slot),

    CONSTRAINT fk_match_player_state_match
        FOREIGN KEY (match_id)
        REFERENCES matches.match(match_id),

    CONSTRAINT chk_match_player_state_slot
        CHECK (player_slot IN (1, 2))
);


-- =========================================================
-- SCHEMA: AUDIT
-- =========================================================

CREATE TABLE audit.audit_log (
    audit_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER,
    action VARCHAR(50) NOT NULL,
    table_name VARCHAR(100) NOT NULL,
    record_id TEXT NOT NULL,
    old_values TEXT,
    new_values TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_audit_log_user
        FOREIGN KEY (user_id)
        REFERENCES security."user"(user_id)
);
